name: Go Backend CI # CI CD workflows

on:
  push:
    branches: [ main ] # Trigger on pushes to main and feature branches
    paths:
      - 'go-backend/**' # Trigger only when changes occur in the backend directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: go mod download

    - name: Run linting
      run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./...

    - name: Run unit tests
      run: go test -v ./...
