name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: |
          cd backend
          go mod download
          go get github.com/stretchr/testify/assert

      - name: Run unit tests
        run: |
          cd backend
          go test ./tests/unit/...

      - name: Run integration tests
        run: |
          cd backend
          go test ./tests/integration/...
