name: Backend CI

on:
  push:
    paths:
      - 'myapp/backend/**' # Adjust the path according to your folder structure
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        path: myapp

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download
        working-directory: myapp/backend

      - name: Run unit tests
        run: go test ./tests/unit/...
        working-directory: myapp/backend

      - name: Run integration tests
        run: go test ./tests/integration/...
        working-directory: myapp/backend
