name: Next.js Frontend CI

on:
  push:
    branches: [ main ] # Trigger on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to frontend directory
      run: cd nextjs-frontend

    - name: Install dependencies
      run: |
        npm install
        npm install eslint eslint-config-next --save-dev

    - name: Run linting
      run: npm run lint

    - name: Run unit tests
      run: npm test
