name: Build Next.js Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd Inc42Assignmnet/nextjs-frontend
          npm install

      - name: Lint code
        run: |
          cd Inc42Assignmnet/nextjs-frontend
          npm run lint

      - name: Build project
        run: |
          cd Inc42Assignmnet/nextjs-frontend
          npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: Inc42Assignmnet/nextjs-frontend/.next

  deploy:
    name: Deploy to hosting service
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-build
          path: Inc42Assignmnet/nextjs-frontend/.next

      # Add your deployment steps here, such as deploying to a hosting service like Vercel or Netlify
