name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Next.js App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Navigate to frontend directory
        run: cd nextjs-frontend
        working-directory: ./Inc42Assignmnet/nextjs-frontend

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
