name: Install WPCS

on:
  push:
    branches: [ main ] # Trigger the workflow on pushes to the main branch
  workflow_dispatch:   # Allow manual triggering of the workflow

jobs:
  install-wpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Allow dealerdirect/phpcodesniffer-composer-installer plugin globally
        run: composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install WPCS
        run: composer global require "wp-coding-standards/wpcs:*"
