name: WordPress PHP CI

on:
  push:
    branches: [ main ] # Trigger on pushes to main and feature branches
    paths:
      - 'wordpress-blog/**' # Trigger only when changes occur in the wordpress directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install WordPress Coding Standards
      run: composer global require squizlabs/php_codesniffer

    - name: Run PHPCS
      run: phpcs --standard=WordPress ./wordpress

    # Add additional steps for unit tests or other checks as needed
