name: WordPress PHP CI

on:
  push:
    branches: [main] 
    paths:
      - 'wordpress-blog/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install WordPress Coding Standards
      run: |
        composer global require wp-coding-standards/wpcs
        ~/.composer/vendor/bin/phpcs --config-set installed_paths /home/runner/.composer/vendor/wp-coding-standards/wpcs

    - name: Run PHPCS
      run: ~/.composer/vendor/bin/phpcs --standard=WordPress ./wordpress-blog

    # Add additional steps for unit tests or other checks as needed
